---
- name: Update cache
  apt: 
    update_cache: yes

- name: Install apt-transport-https and certificates
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install Docker APT key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main

- name: Update cache and install Docker engine
  apt:
    update_cache: yes
    name: docker-engine=1.11.2-0~jessie
    state: present
